# NumPy

In [ ]:
'''
NumPy -> Numeric Python
Numpy is also denote as [].
'''

In [1]:
import numpy as np

In [4]:
num1 = [1, 2, 3, 4, 5]
num2 = [6, 7, 8, 9, 10]
print(num1)
num3 = num1 + num2
print(num3)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
# python -> List
# NumPy -> Array

In [5]:
num1_array = np.array(num1)
num2_array = np.array(num2)
print(num1_array)
print(num2_array)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [14]:
num_sum = num1_array + num2_array
print(num_sum)

[ 7  9 11 13 15]


## 1D Array

In [15]:
one_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
one_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## 2D Array

In [16]:
two_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
two_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Slicing

In [20]:
one_array[1:5]

array([2, 3, 4, 5])

In [21]:
two_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
for num in two_array[1:3]:
    print(num[1:3])

[5 6]
[8 9]


In [26]:
two_array[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [30]:
one_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [31]:
one_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Arange

In [37]:
# python for loop - range()
num = []
for i in range(1, 11):
    num.append(i)
num = np.array(num)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
numbers = np.arange(1, 11)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Reshape and Ravel

In [38]:
'''
Reshape -> Reshape any dimension of array into another dimension array.
Ravel -> Convert multi dimensional array into 1D array
'''

'\nReshape -> Reshape any dimension of array into another dimension array.\nRavel -> Convert multi dimensional array into 1D array\n'

In [3]:
numbers = np.arange(1, 61)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [4]:
reshape_numbers = numbers.reshape(12, 5)
reshape_numbers

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60]])

In [45]:
# Flatten
ravel_number = reshape_numbers.ravel()
ravel_number

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

## Array Broadcasting

In [ ]:
'''
Rules of Broadcasting
-----------------------
1. All shape and size of array must be equal.
2. Atleast one array of shape and size must be 2 other should be equal.
'''

In [50]:
num1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]) # 3 x 3

In [58]:
num2 = np.array([
    [9]
]) # 1 x 1

In [59]:
num1 + num2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

## Boolean Indexing

In [5]:
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [7]:
# find all numbers that are greater than 50.
filter_numbers = numbers > 50
filter_numbers

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [67]:
numbers[filter_numbers]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [70]:
fruits = np.array(['Apple', 'Banana', 'Apple', 'Coconut', 'Apple', 'Mango', 'Watermelon'])
fruits

array(['Apple', 'Banana', 'Apple', 'Coconut', 'Apple', 'Mango',
       'Watermelon'], dtype='<U10')

In [71]:
filter_fruits = fruits == 'Apple'
filter_fruits

array([ True, False,  True, False,  True, False, False])

In [72]:
fruits[filter_fruits]

array(['Apple', 'Apple', 'Apple'], dtype='<U10')

In [ ]:
# C Program
# Pandas
# Matplotlib
# Seaborn
# Plotly